### ISSUE TITLE
Enable CSRF Token acceptance

### ISSUE THREAD

**Issue by kblizeck** [themccallister/craft.cache-clear#3]
I am trying to sent an HTTP POST to my cache-clear URL through DeployBot (which only allows POST). 
I have CSRF Tokens enabled on the site and I am receiving the following error when I try to hit the cache-clear URL : "Bad Request: The CSRF token could not be verified."

Do you have a way to check if CSRF tokens are enabled, and if so, send that data to Craft?

Thanks!

**Comment by jasonmccallister** [comment]
Hi @kblizeck! 

The CSRF protection is done at the server side which would require the form be processed on the actual site, since we are sending a POST from offsite (DeployBot), we will not have access to the CSRF token generated in the Craft forms. You can see more about CSRF on this support page: https://craftcms.com/support/csrf-protection

One way to do this, which I would not really recommend based on how many forms your site has, is to disable CSRF protection on forms. That can be found here: https://craftcms.com/docs/config-settings#enableCsrfProtection

There may still be a way to do this, but it would require manually editing the `general.php` file. That step to edit the config file is explained in more detail here: https://craftcms.stackexchange.com/a/4554

**Comment by jasonmccallister** [comment]
Let me know if you have any additional questions, otherwise I am going to close this out.
